services:
  # Backend API Service
  - type: web
    name: agentic-workstation-backend
    env: docker
    plan: starter
    buildCommand: cd backend && ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar backend/target/agenticworkstation-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JPA_SHOW_SQL
        value: false
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
      - key: DATABASE_URL
        fromDatabase:
          name: agentic-workstation-db
          property: connectionString
    healthCheckPath: /health

  # Frontend Static Site
  - type: web
    name: agentic-workstation-frontend
    env: static
    buildCommand: cd frontend && flutter build web --web-renderer html --release
    staticPublishPath: frontend/build/web
    envVars:
      - key: FLUTTER_WEB_RENDERER
        value: html
      - key: FLUTTER_BUILD_MODE
        value: release

databases:
  - name: agentic-workstation-db
    databaseName: agentic_workstation
    user: agentic_user
    plan: starter